- id: '1755095587104'
  alias: Skru på lys i bod
  description: ''
  triggers:
  - entity_id: binary_sensor.bod_dorkontakt_contact
    to: 'on'
    trigger: state
  actions:
  - target:
      area_id: bod
    action: light.turn_on
  - delay: 00:05:00
  - repeat:
      count: 3
      sequence:
      - target:
          area_id: bod
        action: light.turn_off
      - delay: '00:00:0.3'
      - target:
          area_id: bod
        action: light.turn_on
      - delay: '00:00:0.3'
  - delay: 00:00:30
  - target:
      area_id: bod
    action: light.turn_off
  mode: restart
- id: '1755096364674'
  alias: Alarm påskrudd - skru av alt lys
  description: ''
  triggers:
  - device_id: 2cc859fc07f9ebc270774f733eb0ac5e
    domain: alarm_control_panel
    entity_id: 67d4879e58839cbc3062e2d548e9b112
    type: armed_away
    trigger: device
  conditions: []
  actions:
  - sequence:
    - action: script.lys_alt_av
      data: {}
  mode: single
- id: '1755152263990'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - action: notify.mobile_app_sm_s928b
        metadata: {}
        data:
          message: Lavt batterinivå
      threshold: 90
- id: '1756886867339'
  alias: Bryter Kjøkken Trykk Opp
  description: ''
  triggers:
  - domain: mqtt
    device_id: 914cdb659490b0dd4df545371e11ce76
    type: button_short_release
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.oppholdsrom_matlaging
  mode: single
- id: '1757109258111'
  alias: kjøkken.alt_av
  description: ''
  triggers:
  - domain: mqtt
    device_id: 914cdb659490b0dd4df545371e11ce76
    type: button_short_release
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.kjokken_alt_av
  mode: single
- id: '1757193667498'
  alias: Alarm deaktivert (inkl. via disarming)
  triggers:
  - entity_id: alarm_control_panel.verisure_alarm
    from: armed_away
    to: disarmed
    trigger: state
  - entity_id: alarm_control_panel.verisure_alarm
    from: disarming
    to: disarmed
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id: script.lys_dagtid_avskrudd_alarm
    action: script.turn_on
  mode: single
- id: '1757876919478'
  alias: Stue klima – reguler settpunkt på Daikin
  description: ''
  triggers:
  - minutes: /5
    trigger: time_pattern
  - entity_id:
    - sensor.stue_target_pumpesettpunkt
    - sensor.stue_temperatur_virtuell
    - sensor.ute_temperatur_virtuell
    - input_number.stue_onsket_temp
    trigger: state
  - value_template: "{{ states('sensor.stue_temperatur_virtuell')|float(9999)\n  <
      (states('input_number.stue_onsket_temp')|float - 0.05) }}\n"
    trigger: template
  - value_template: "{{ states('sensor.stue_temperatur_virtuell')|float(-9999)\n  >
      (states('input_number.stue_onsket_temp')|float + 0.05) }}\n"
    trigger: template
  conditions:
  - condition: state
    entity_id: input_boolean.stue_klima_hold
    state: 'off'
  - condition: template
    value_template: '{{ states(''sensor.stue_target_pumpesettpunkt'')|float(none)
      is not none }}'
  - condition: template
    value_template: '{{ states(''climate.daikinap86694'') not in [''unavailable'',''unknown'']
      }}'
  - condition: template
    value_template: '{{ is_state(''timer.stue_klima_cooldown'',''idle'') }}'
  actions:
  - variables:
      daikin: climate.daikinap86694
      target: '{{ states(''sensor.stue_target_pumpesettpunkt'')|float(22.0) }}'
      current_set: '{% set t = state_attr(''climate.daikinap86694'',''temperature'')
        %} {{ (t if t is number else states(''sensor.stue_target_pumpesettpunkt'')|float(22.0))|float
        }}

        '
      max_step: '{{ states(''input_number.stue_setpunkt_endringsgrense'')|float(1.0)
        }}'
      min_effective_delta: 0.2
  - variables:
      delta: '{{ target - current_set }}'
      next_set: "{% if (delta | abs) <= max_step %}\n  {{ target }}\n{% else %}\n
        \ {{ (current_set + max_step) if (delta > 0) else (current_set - max_step)
        }}\n{% endif %}\n"
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ (target - current_set) | abs >= min_effective_delta }}'
      sequence:
      - if:
        - condition: template
          value_template: '{{ states(daikin) != ''heat'' }}'
        then:
        - target:
            entity_id: '{{ daikin }}'
          data:
            hvac_mode: heat
          action: climate.set_hvac_mode
      - target:
          entity_id: '{{ daikin }}'
        data:
          temperature: '{{ next_set | round(1) }}'
        action: climate.set_temperature
      - event: stue_klima_sett_ok
        event_data:
          from: '{{ current_set | round(1) }}'
          to: '{{ next_set | round(1) }}'
      - data:
          name: Stue klima (Daikin)
          message: '"Endrer setpunkt fra {{ current_set|round(1) }} → {{ next_set|round(1)
            }} (target: {{ target|round(1) }}, delta: {{ (target-current_set)|round(2)
            }})"

            '
          entity_id: climate.daikinap86694
        action: logbook.log
    - conditions:
      - condition: template
        value_template: '{{ (target - current_set) | abs < min_effective_delta }}'
      sequence:
      - data:
          name: Stue klima (Daikin)
          message: '"Ingen endring: current {{ current_set|round(1) }}≈target {{ target|round(1)
            }} (terskel: {{ min_effective_delta }})"

            '
          entity_id: climate.daikinap86694
        action: logbook.log
  mode: restart
  trace:
    stored_traces: 10
