- id: '1755095587104'
  alias: Skru på lys i bod
  description: ''
  triggers:
  - entity_id: binary_sensor.bod_dorkontakt_contact
    to: 'on'
    trigger: state
  actions:
  - target:
      area_id: bod
    action: light.turn_on
  - delay: 00:05:00
  - repeat:
      count: 3
      sequence:
      - target:
          area_id: bod
        action: light.turn_off
      - delay: '00:00:0.3'
      - target:
          area_id: bod
        action: light.turn_on
      - delay: '00:00:0.3'
  - delay: 00:00:30
  - target:
      area_id: bod
    action: light.turn_off
  mode: restart
- id: '1755096364674'
  alias: Alarm påskrudd - skru av alt lys
  description: ''
  triggers:
  - device_id: 2cc859fc07f9ebc270774f733eb0ac5e
    domain: alarm_control_panel
    entity_id: 67d4879e58839cbc3062e2d548e9b112
    type: armed_away
    trigger: device
  conditions: []
  actions:
  - sequence:
    - action: script.lys_alt_av
      data: {}
  mode: single
- id: '1755152263990'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - action: notify.mobile_app_sm_s928b
        metadata: {}
        data:
          message: Lavt batterinivå
      threshold: 90
- id: '1756886867339'
  alias: Bryter Kjøkken Trykk Opp
  description: ''
  triggers:
  - domain: mqtt
    device_id: 914cdb659490b0dd4df545371e11ce76
    type: button_short_release
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.oppholdsrom_matlaging
  mode: single
- id: '1757109258111'
  alias: kjøkken.alt_av
  description: ''
  triggers:
  - domain: mqtt
    device_id: 914cdb659490b0dd4df545371e11ce76
    type: button_short_release
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.kjokken_alt_av
  mode: single
- id: '1757193667498'
  alias: Alarm deaktivert (inkl. via disarming)
  triggers:
  - entity_id: alarm_control_panel.verisure_alarm
    from: armed_away
    to: disarmed
    trigger: state
  - entity_id: alarm_control_panel.verisure_alarm
    from: disarming
    to: disarmed
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id: script.lys_dagtid_avskrudd_alarm
    action: script.turn_on
  mode: single
