homeassistant:
  customize:
    sensor.stue_target_pumpesettpunkt:
      friendly_name: "Stue: beregnet setpunkt til varmepumpe (Daikin)"

# ====== Tuning / grenser ======
input_number:
  stue_onsket_temp:
    name: "Stue: ønsket temp (sittehøyde)"
    min: 15
    max: 24
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermometer

  stue_base_offset_a:
    name: "Stue offset base a"
    min: -2
    max: 4
    step: 0.1
    icon: mdi:tune-variant

  stue_kulde_slope_b:
    name: "Stue offset kuldeslope b (°C pr °C under terskel)"
    min: 0
    max: 0.5
    step: 0.01
    icon: mdi:chart-spline

  stue_kulde_terskel:
    name: "Stue offset kulde-terskel (°C)"
    min: -10
    max: 25
    step: 1
    icon: mdi:snowflake-thermometer

  stue_kp:
    name: "Stue P-forsterkning (Kp)"
    min: 0
    max: 1
    step: 0.05
    icon: mdi:alpha-p-box

  stue_min_setpunkt:
    name: "Stue min setpunkt (Daikin)"
    min: 15
    max: 22
    step: 0.5
    unit_of_measurement: "°C"

  stue_max_setpunkt:
    name: "Stue max setpunkt (Daikin)"
    min: 22
    max: 30
    step: 0.5
    unit_of_measurement: "°C"

  stue_setpunkt_endringsgrense:
    name: "Maks endring per justering"
    min: 0.5
    max: 3
    step: 0.5
    unit_of_measurement: "°C"

  # --- D-LEDD: Tuning ---
  stue_kd:
    name: "Stue D-forsterkning (Kd)"
    min: 0
    max: 5
    step: 0.1
    icon: mdi:alpha-d-box
  stue_deriv_threshold:
    name: "Stue D terskel (°C/min)"
    min: 0
    max: 0.2
    step: 0.005
    icon: mdi:sigma-lower
  stue_deriv_cap:
    name: "Stue D maks bidrag (°C)"
    min: 0
    max: 3
    step: 0.1
    icon: mdi:speedometer

input_boolean:
  stue_klima_hold:
    name: "Stue klima HOLD (pause regulering)"
    icon: mdi:pause-octagon

# ====== Beregninger ======
# --- D-LEDD: stigningshastighet for romtemperatur ---
sensor:
  - platform: derivative
    source: sensor.stue_temperatur_virtuell
    name: "Stue temp stigning"
    unit_time: min # resultat i °C/min
    time_window: "00:10:00" # 10-minutters vindu
    round: 3

template:
  - sensor:
      - name: "Stue target pumpesettpunkt"
        unique_id: stue_target_pumpesettpunkt
        unit_of_measurement: "°C"
        state: >
          {# Inndata #}
          {% set desired = states('input_number.stue_onsket_temp')|float(21.5) %}
          {% set Tin = states('sensor.stue_temperatur_virtuell')|float(default=desired) %}
          {% set Tout = states('sensor.ute_temperatur_virtuell')|float(10.0) %}

          {# Feed-forward #}
          {% set a  = states('input_number.stue_base_offset_a')|float(1.0) %}
          {% set b  = states('input_number.stue_kulde_slope_b')|float(0.10) %}
          {% set Tt = states('input_number.stue_kulde_terskel')|float(15.0) %}
          {% set cold = max(0, Tt - Tout) %}
          {% set offset_ff = a + b * cold %}

          {# P-ledd #}
          {% set Kp = states('input_number.stue_kp')|float(0.30) %}
          {% set error = desired - Tin %}
          {% set corr_p = Kp * error %}

          {# --- D-LEDD: prediktivt ledd mot stigning/fall --- #}
          {% set dTdt = states('sensor.stue_temp_stigning')|float(0.0) %}       {# °C/min #}
          {% set Kd = states('input_number.stue_kd')|float(0.0) %}
          {% set d_thr = states('input_number.stue_deriv_threshold')|float(0.03) %}
          {% set d_cap = states('input_number.stue_deriv_cap')|float(1.5) %}
          {# Bare reager når |stigning| > terskel; negativ dTdt (fall) gir positivt D-bidrag #}
          {% set d_raw = ( -Kd * dTdt ) if (dTdt|abs > d_thr) else 0 %}
          {% set corr_d = [d_cap, [-d_cap, d_raw]|max]|min %}

          {# Sum og begrensning #}
          {% set raw_target = desired + offset_ff + corr_p + corr_d %}
          {% set tmin = states('input_number.stue_min_setpunkt')|float(18.0) %}
          {% set tmax = states('input_number.stue_max_setpunkt')|float(28.0) %}
          {% set clamped = [tmax, [tmin, raw_target]|max]|min %}

          {{ clamped | round(1) }}

      - name: "Stue temperaturfeil"
        unique_id: stue_temp_error
        unit_of_measurement: "°C"
        state: >
          {{ (states('input_number.stue_onsket_temp')|float(21.5)
              - states('sensor.stue_temperatur_virtuell')|float(21.5)) | round(2) }}

      # --- D-LEDD: eksponér D-bidraget for diagnose (valgfritt i UI) ---
      - name: "Stue D-bidrag"
        unique_id: stue_d_contrib
        unit_of_measurement: "°C"
        state: >
          {% set dTdt = states('sensor.stue_temp_stigning')|float(0.0) %}
          {% set Kd = states('input_number.stue_kd')|float(0.0) %}
          {% set d_thr = states('input_number.stue_deriv_threshold')|float(0.03) %}
          {% set d_cap = states('input_number.stue_deriv_cap')|float(1.5) %}
          {% set d_raw = ( -Kd * dTdt ) if (dTdt|abs > d_thr) else 0 %}
          {{ ([d_cap, [ -d_cap, d_raw ]|max]|min) | round(2) }}

# ====== Antisjattering (rate limit) ======
timer:
  stue_klima_cooldown:
    duration: "00:10:00"

# ====== Regulering mot Daikin ======
automation:
  - id: stue_klima_regulering_daikin
    alias: "Stue klima – reguler settpunkt på Daikin"
    mode: restart
    trigger:
      # Heartbeat
      - platform: time_pattern
        minutes: "/5"

      # Endring i relevante sensorer
      - platform: state
        entity_id:
          - sensor.stue_target_pumpesettpunkt
          - sensor.stue_temperatur_virtuell
          - sensor.ute_temperatur_virtuell
          - sensor.stue_temp_stigning # --- D-LEDD: legg til derivative
          - input_number.stue_onsket_temp
          - input_number.stue_kd # --- D-LEDD: retuning skal trigge
          - input_number.stue_deriv_threshold
          - input_number.stue_deriv_cap

      # Kryssing UNDER ønsket temp (med hysterese)
      - platform: template
        value_template: >
          {{ states('sensor.stue_temperatur_virtuell')|float(9999)
            < (states('input_number.stue_onsket_temp')|float - 0.05) }}

      # Kryssing OVER ønsket temp (med hysterese)
      - platform: template
        value_template: >
          {{ states('sensor.stue_temperatur_virtuell')|float(-9999)
            > (states('input_number.stue_onsket_temp')|float + 0.05) }}

    condition:
      - condition: state
        entity_id: input_boolean.stue_klima_hold
        state: "off"
      - condition: template
        value_template: "{{ states('sensor.stue_target_pumpesettpunkt')|float(none) is not none }}"
      - condition: template
        value_template: "{{ states('climate.daikinap86694') not in ['unavailable','unknown'] }}"
      - condition: template
        value_template: "{{ is_state('timer.stue_klima_cooldown','idle') }}"
    action:
      - variables:
          daikin: "climate.daikinap86694"
          target: "{{ states('sensor.stue_target_pumpesettpunkt')|float(22.0) }}"
          current_set: >
            {% set t = state_attr('climate.daikinap86694','temperature') %}
            {{ (t if t is number else states('sensor.stue_target_pumpesettpunkt')|float(22.0))|float }}
          max_step: "{{ states('input_number.stue_setpunkt_endringsgrense')|float(1.0) }}"
          min_effective_delta: 0.2
          dterm: "{{ states('sensor.stue_d_bidrag')|default(states('sensor.stue_d-bidrag')) }}"
      - variables:
          delta: "{{ target - current_set }}"
          next_set: >
            {% if (delta | abs) <= max_step %}
              {{ target }}
            {% else %}
              {{ (current_set + max_step) if (delta > 0) else (current_set - max_step) }}
            {% endif %}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ (target - current_set) | abs >= min_effective_delta }}"
            sequence:
              - if:
                  - condition: template
                    value_template: "{{ states(daikin) != 'heat' }}"
                then:
                  - service: climate.set_hvac_mode
                    target: { entity_id: "{{ daikin }}" }
                    data: { hvac_mode: heat }
              - service: climate.set_temperature
                target: { entity_id: "{{ daikin }}" }
                data:
                  temperature: "{{ next_set | round(1) }}"
              - event: stue_klima_sett_ok
                event_data:
                  from: "{{ current_set | round(1) }}"
                  to: "{{ next_set | round(1) }}"
              - service: logbook.log
                data:
                  name: "Stue klima (Daikin)"
                  message: >
                    Endrer setpunkt {{ current_set|round(1) }} → {{ next_set|round(1) }}
                    (target: {{ target|round(1) }}, Δ: {{ (target-current_set)|round(2) }},
                    dT/dt: {{ states('sensor.stue_temp_stigning') }} °C/min,
                    D: {{ states('sensor.stue_d-bidrag') | default(states('sensor.stue_d_bidrag')) }} °C)
                  entity_id: climate.daikinap86694

          - conditions:
              - condition: template
                value_template: "{{ (target - current_set) | abs < min_effective_delta }}"
            sequence:
              - service: logbook.log
                data:
                  name: "Stue klima (Daikin)"
                  message: >
                    Ingen endring: current {{ current_set|round(1) }}≈target {{ target|round(1) }}
                    (terskel: {{ min_effective_delta }},
                    dT/dt: {{ states('sensor.stue_temp_stigning') }} °C/min,
                    D: {{ states('sensor.stue_d-bidrag') | default(states('sensor.stue_d_bidrag')) }} °C)
                  entity_id: climate.daikinap86694

    trace:
      stored_traces: 10
